version: "3.8"
services:
  client:
    image: akashp27/mblog-client:0.0.4.RELEASE
    env_file:
      - ./client/.env
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-network
    volumes:
      - "./client/:/usr/src/app"
      - /usr/src/app/node_modules

  api:
    image: akashp27/mblog-api:0.0.4.RELEASE
    env_file:
      - ./.env
    build: ./
    ports:
      - "5500:5500"
    networks:
      - mern-network
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
